"""
circuit-backend/main.py
========================
Single-route FastAPI server that accepts a resistive-circuit netlist,
writes a SPICE deck, runs it through ngspice, parses the output, and
returns branch currents (in Amperes).

Run:
    uvicorn main:app --reload --port 8000

Prerequisites:
    pip install fastapi uvicorn
    ngspice must be on PATH  (or set NGSPICE_PATH env var)
"""

import json
import os
import re
import subprocess
import tempfile
from pathlib import Path
from typing import Any

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# ---------------------------------------------------------------------------
# App setup
# ---------------------------------------------------------------------------
app = FastAPI(title="Circuit Simulator Backend")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],          # tighten for production
    allow_methods=["POST", "GET"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Request / response models  (mirror src/api/simulate.ts)
# ---------------------------------------------------------------------------

class NetlistComponent(BaseModel):
    id: str
    ref: str
    type: str
    nodes: list[str]
    params: dict[str, float]


class Netlist(BaseModel):
    version: int
    components: list[NetlistComponent]
    nets: list[str]


class TransientConfig(BaseModel):
    stepSeconds: float
    stopSeconds: float


class AcConfig(BaseModel):
    startHz: float
    stopHz: float
    pointsPerDecade: int


class Analysis(BaseModel):
    mode: str                    # "dc" | "tran" | "ac"
    tran: TransientConfig | None = None
    ac: AcConfig | None = None


class SimulateRequest(BaseModel):
    netlist: Netlist
    analysis: Analysis


class SimulationResult(BaseModel):
    ok: bool
    message: str | None = None
    traces: dict[str, list[float]] | None = None

# ---------------------------------------------------------------------------
# SPICE deck builder   (resistive circuits → DC operating point)
# ---------------------------------------------------------------------------

_TYPE_TO_SPICE = {
    "resistor":   "R",
    "capacitor":  "C",
    "inductor":   "L",
    "vsource_dc": "V",
    "vsource_ac": "V",
    "battery":    "V",
    "vsource_dep": "V",   # control not captured: simulated at its set voltage
    "diode":      "D",
    "ground":     None,   # node marker only
}


def _build_spice_deck(netlist: Netlist) -> str:
    """Convert our JSON netlist to a SPICE deck string.

    For a purely resistive circuit we always run a DC operating-point (.op)
    so we get branch currents directly from ngspice.
    """
    lines: list[str] = ["* Auto-generated by circuit-backend"]

    voltage_sources: list[str] = []
    uses_diode = False

    for comp in netlist.components:
        prefix = _TYPE_TO_SPICE.get(comp.type)
        if prefix is None:
            continue

        nodes = " ".join(comp.nodes)

        if comp.type == "resistor":
            r = comp.params.get("resistance", 1000)
            lines.append(f"R{comp.ref.lstrip('R')} {nodes} {r}")

        elif comp.type == "capacitor":
            c = comp.params.get("capacitance", 1e-6)
            lines.append(f"C{comp.ref.lstrip('C')} {nodes} {c}")

        elif comp.type == "inductor":
            l = comp.params.get("inductance", 1e-3)
            lines.append(f"L{comp.ref.lstrip('L')} {nodes} {l}")

        elif comp.type == "vsource_dc":
            v = comp.params.get("voltage", 5)
            lines.append(f"V{comp.ref.lstrip('V')} {nodes} DC {v}")
            voltage_sources.append(comp.ref)

        elif comp.type in ("battery", "vsource_dep"):
            v = comp.params.get("voltage", 5)
            name = comp.ref if comp.ref.startswith("V") else f"V{comp.ref}"
            lines.append(f"{name} {nodes} DC {v}")
            voltage_sources.append(name)

        elif comp.type == "diode":
            lines.append(f"D{comp.ref.lstrip('D')} {nodes} DMOD")
            uses_diode = True

        elif comp.type == "vsource_ac":
            v = comp.params.get("voltage", 1)
            freq = comp.params.get("frequency", 50)
            lines.append(f"V{comp.ref.lstrip('V')} {nodes} AC {v} SIN(0 {v} {freq})")
            voltage_sources.append(comp.ref)

    if uses_diode:
        # 1N4148-like small-signal diode
        lines.append(".model DMOD D(IS=2.52n RS=0.568 N=1.752)")

    # DC operating point — gives I(Vx) for every voltage source
    lines.append(".op")
    lines.append(".end")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# ngspice runner
# ---------------------------------------------------------------------------

NGSPICE = os.environ.get("NGSPICE_PATH", "ngspice")


def _run_ngspice(spice_deck: str) -> str:
    """Write a temp .cir file, run ngspice, return stdout."""
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".cir", delete=False, encoding="utf-8"
    ) as f:
        f.write(spice_deck)
        cir_path = f.name

    try:
        result = subprocess.run(
            [NGSPICE, "-b", cir_path],        # -b = batch mode (no GUI)
            capture_output=True,
            text=True,
            timeout=30,
        )
        output = result.stdout + result.stderr
        return output
    finally:
        Path(cir_path).unlink(missing_ok=True)


# ---------------------------------------------------------------------------
# Output parser
# ---------------------------------------------------------------------------

_CURRENT_RE = re.compile(
    r"i\(v(\w+)\)\s*=\s*([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)",
    re.IGNORECASE,
)

_NODE_VOLTAGE_RE = re.compile(
    r"v\((\w+)\)\s*=\s*([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)",
    re.IGNORECASE,
)


def _parse_op_output(raw: str) -> dict[str, float]:
    """Extract DC operating-point values from ngspice -b output."""
    results: dict[str, float] = {}

    for m in _CURRENT_RE.finditer(raw):
        label = f"I(V{m.group(1).upper()})"
        value = float(m.group(2))
        results[label] = value

    for m in _NODE_VOLTAGE_RE.finditer(raw):
        label = f"V({m.group(1)})"
        value = float(m.group(2))
        results[label] = value

    return results


# ---------------------------------------------------------------------------
# Route
# ---------------------------------------------------------------------------

@app.post("/simulate", response_model=SimulationResult)
async def simulate(req: SimulateRequest) -> Any:
    """
    Accepts the JSON netlist produced by the frontend, runs a DC
    operating-point simulation via ngspice, and returns branch currents
    (and node voltages) as scalar traces.

    For a resistive circuit the result is a single operating-point value,
    so each trace contains exactly one element.
    """
    # --- Build the SPICE deck ---
    spice = _build_spice_deck(req.netlist)
    print("\n=== SPICE deck ===")
    print(spice)
    print("==================\n")

    # --- Run ngspice ---
    try:
        raw_output = _run_ngspice(spice)
    except FileNotFoundError:
        raise HTTPException(
            status_code=500,
            detail=(
                f"ngspice not found at '{NGSPICE}'. "
                "Install ngspice and make sure it is on your PATH, "
                "or set the NGSPICE_PATH environment variable."
            ),
        )
    except subprocess.TimeoutExpired:
        raise HTTPException(status_code=500, detail="ngspice timed out.")

    print("=== ngspice raw output ===")
    print(raw_output)
    print("==========================\n")

    # --- Parse results ---
    op_values = _parse_op_output(raw_output)

    if not op_values:
        # ngspice ran but produced no parseable numbers → return the raw log
        return SimulationResult(
            ok=False,
            message=f"ngspice ran but no values were parsed.\n\nRaw output:\n{raw_output}",
        )

    # --- Console-log the current values (Amperes) as requested ---
    print("=== Branch currents (Amperes) ===")
    for label, value in op_values.items():
        if label.startswith("I("):
            print(f"  {label} = {value:.6e} A")
    print("=================================\n")

    # Wrap scalars in single-element lists so the frontend trace format is happy
    traces: dict[str, list[float]] = {k: [v] for k, v in op_values.items()}

    return SimulationResult(ok=True, traces=traces)


# ---------------------------------------------------------------------------
# Drawn circuit → netlist (circuitmodel YOLO pipeline)
# ---------------------------------------------------------------------------

class GenerateCircuitRequest(BaseModel):
    image: str                   # PNG/JPEG as base64 or a data: URL
    title: str = "drawn-circuit"


def _decode_request_image(req: GenerateCircuitRequest):
    import base64
    import binascii

    from recognizer import decode_image

    payload = req.image.split(",", 1)[1] if req.image.startswith("data:") else req.image
    try:
        data = base64.b64decode(payload, validate=True)
    except binascii.Error:
        raise HTTPException(status_code=400, detail="Image is not valid base64.")
    return decode_image(data)


@app.post("/detect-components")
def detect_components(req: GenerateCircuitRequest) -> dict[str, Any]:
    """
    Component detection only, for run-time processing while the user draws:
    returns each detected symbol's class, confidence and box (image pixels).
    """
    from recognizer import RecognitionError, detect_boxes

    image = _decode_request_image(req)
    try:
        boxes = detect_boxes(image)
    except RecognitionError as e:
        raise HTTPException(status_code=422, detail=str(e))
    h, w = image.shape[:2]
    return {
        "image_width": w,
        "image_height": h,
        "detections": [
            {"type": b.cls_name, "conf": round(b.conf, 3),
             "bbox": {"x1": b.x1, "y1": b.y1, "x2": b.x2, "y2": b.y2}}
            for b in boxes
        ],
    }


@app.post("/generate-circuit")
def generate_circuit(req: GenerateCircuitRequest) -> dict[str, Any]:
    """
    Accepts an image of a hand-drawn circuit (e.g. the frontend's drawing
    canvas), runs it through the circuitmodel pipeline, and returns the
    netlist JSON in the same format as circuitmodel's netlist.json.
    """
    from recognizer import RecognitionError, recognize

    image = _decode_request_image(req)
    try:
        return recognize(image, title=req.title)
    except RecognitionError as e:
        raise HTTPException(status_code=422, detail=str(e))


# ---------------------------------------------------------------------------
# Quick health-check
# ---------------------------------------------------------------------------

@app.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok"}
